import type { Snapshot } from './types';
import { monthOf, today } from './finance';
export function defaults(): Snapshot {
  const start = monthOf(today());
  const rows: [string, string, number, 'flexible' | 'fixed' | 'business', boolean, string][] = [
    ['luke', 'Luke', 50, 'flexible', true, '#467dcd'], ['samantha', 'Samantha', 50, 'flexible', true, '#b46b91'], ['dates', 'Dates', 100, 'flexible', false, '#b68636'], ['gas', 'Gas', 175, 'flexible', false, '#548a78'], ['household', 'Household & Kids', 150, 'flexible', false, '#7576a6'], ['carwash', 'Car wash', 15, 'flexible', false, '#548a78'], ['offering', 'Fast offering', 25, 'flexible', false, '#467dcd'], ['medical', 'Medical', 10, 'flexible', false, '#b46b91'], ['food', 'Food cash', 0, 'flexible', false, '#b68636'],
    ['electricity', 'Electricity', 350, 'fixed', false, '#548a78'], ['water', 'Water', 45, 'fixed', false, '#467dcd'], ['trash', 'Trash', 31, 'fixed', false, '#7576a6'], ['internet', 'WOW internet', 92, 'fixed', false, '#548a78'], ['insurance', 'Car insurance', 102, 'fixed', false, '#467dcd'], ['gym', 'Gym', 13, 'fixed', false, '#b68636'], ['chatgpt', 'ChatGPT', 20, 'fixed', false, '#7576a6'], ['pgsharp', 'PGSharp', 5, 'fixed', false, '#b46b91'], ['shopify', 'Shopify', 41.91, 'business', false, '#548a78'], ['epidemic', 'Epidemic Sound', 17.99, 'business', false, '#b68636'],
  ];
  return { categories: rows.map(([id, name, amount, group, rollover, color]) => ({ id, name, monthly_cents: Math.round(amount * 100), group, rollover, color, start_month: start })), limits: [], transactions: [], accounts: [], tasks: [
    ['internet', 'Lower WOW internet', 'Luke', 'Current plan is approximately $92 per month.'], ['audit', 'Arrange Georgia Power assessment', 'Samantha', 'Review the temporary $350 electricity ceiling after the assessment.'], ['registration', 'Complete vehicle title / registration', 'Luke', 'Enter the confirmed cost and date in Plan.'], ['tuition', 'Enter tuition and funding dates', 'Luke', 'Confirm remaining tuition and when Peach State funding begins.'],
  ].map(([key, title, assignee, notes]) => ({ id: key, title, assignee, notes, status: 'Active', priority: key === 'tuition' ? 'High' : 'Normal', due_date: null, impact_cents: 0, impact_type: 'once', suggestion_key: key, category_id: null, event_id: null })), events: [], reservoir: [], settings: { id: 1, floor_cents: 500000, annual_irregular_cents: 382000, annual_notes: 'Property tax $2,620 + gifts $600 + car maintenance $600. Reduce this allowance when adding the same costs as dated events, to avoid counting them twice. Costco not included until confirmed.', timezone: 'America/New_York', forecast_months: 36 } };
}
