'use client';
import { useState } from 'react';
import { LockKeyhole, ArrowRight } from 'lucide-react';
import { browserDb } from '@/lib/supabase/client';
import { Field, FormError } from './ui';
export function AuthScreen({ configured, allowPreview, preview }: { configured: boolean; allowPreview: boolean; preview: () => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <main className="auth-page"><div className="auth-brand"><img src="/icons/icon-192.png" width="48" height="48" alt=""/><span>Squires<span className="brand-sub">FAMILY FINANCE</span></span></div><section className="auth-content"><div className="eyebrow"><LockKeyhole size={16}/> JUST OUR HOUSEHOLD</div><h1>A little clarity.<br/>More room for life.</h1>{configured ? <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); const f = new FormData(e.currentTarget); try { const { error } = await browserDb().auth.signInWithPassword({ email: String(f.get('email')), password: String(f.get('password')) }); if (error) setError('Email or password was not recognized.'); } catch { setError('Could not connect. Please try again.'); } finally { setBusy(false); } }}><Field label="Email"><input name="email" type="email" autoComplete="username" required/></Field><Field label="Password"><input name="password" type="password" autoComplete="current-password" required/></Field><FormError error={error}/><button className="primary" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'}<ArrowRight size={18}/></button><p className="muted small">Private access for Luke and Samantha.</p></form> : <div><h2>Your household is getting ready.</h2><p className="muted">Private sign-in and shared data will be available once account setup is finished.</p>{allowPreview && <button className="primary" onClick={preview}>Open local preview<ArrowRight size={18}/></button>}</div>}</section><footer className="auth-footer">Squires family &middot; One month at a time.</footer></main>;
}
