'use client';
import { useState } from 'react';
import { ArrowUpRight, Pencil, Plus, RotateCcw } from 'lucide-react';
import { budgetRows, cents, money } from '@/lib/finance';
import type { BudgetRow, Snapshot } from '@/lib/types';
import { Field, FormError, Modal, Submit } from './ui';
export type Save = (action: string, payload: Record<string, unknown>) => Promise<void>;
export function CategoryBar({ row, onClick }: { row: BudgetRow; onClick?: () => void }) {
  const available = row.budget + row.carried;
  return <button className="category-row" onClick={onClick}><div className="row-between"><span className="category-name"><i style={{ background: row.color }}/>{row.name}{row.rollover && <RotateCcw size={12}/>}</span><span><strong className={row.remaining < 0 ? 'negative' : ''}>{money(row.remaining)}</strong><span className="muted small"> left</span></span></div><div className="progress-track"><div style={{ width: Math.min(100, Math.max(0, available > 0 ? row.spent / available * 100 : row.spent > 0 ? 100 : 0)) + '%', background: row.remaining < 0 ? 'var(--red)' : row.color }}/></div><div className="row-between small muted"><span>{money(row.spent)} spent</span><span>of {money(available)}{row.carried !== 0 ? ' incl. rollover' : ''}</span></div></button>;
}
export function Budget({ data, month, save }: { data: Snapshot; month: string; save: Save }) {
  const [editing, setEditing] = useState<BudgetRow | 'new' | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const rows = budgetRows(data, month); const flex = rows.filter(c => c.group === 'flexible');
  return <><div className="section-heading"><div><h2>This month's budget</h2><p className="muted">{money(flex.reduce((a, c) => a + c.remaining, 0))} flexible money left</p></div><button className="secondary" onClick={() => { setEditing('new'); setError(''); }}><Plus size={16}/>Category</button></div>{(['flexible','fixed','business'] as const).map(group => <section className="budget-section" key={group}><div className="section-heading"><h3>{group === 'flexible' ? 'Everyday spending' : group === 'fixed' ? 'Fixed & recurring' : 'Rova / business'}</h3><span className="muted small">{money(rows.filter(r => r.group === group).reduce((a,r) => a+r.budget,0))} / month</span></div><div className="budget-table"><div className="budget-table-head"><span>Category</span><span>Budget</span><span>Spent</span><span>Remaining</span><span/></div>{rows.filter(r => r.group === group).map(r => <button className="budget-table-row" key={r.id} onClick={() => { setEditing(r); setError(''); }}><span className="category-name"><i style={{ background:r.color }}/><span>{r.name}{r.rollover && <small className="muted">{money(r.carried)} rolled forward</small>}</span></span><span>{money(r.budget)}</span><span>{money(r.spent)}</span><strong className={r.remaining<0 ? 'negative' : ''}>{money(r.remaining)}</strong><Pencil size={14}/></button>)}</div></section>)}<p className="footnote"><ArrowUpRight size={14}/>Annual costs and future one-offs are in Plan. Pending purchases are included in spending.</p>{editing && <Modal title={editing === 'new' ? 'Add category' : editing.name} close={() => setEditing(null)}><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(''); try { const amount = cents(String(f.get('amount'))); if (editing === 'new') await save('category', { id: crypto.randomUUID(), name: f.get('name'), group: f.get('group'), monthly_cents: amount, rollover: f.get('rollover') === 'on', start_month: month, color: '#548a78' }); else if (f.get('scope') === 'month') await save('budget', { category_id: editing.id, month, amount_cents: amount }); else { const {budget,carried,spent,pendingSpent,remaining,...category}=editing; void budget;void carried;void spent;void pendingSpent;void remaining; await save('category', {...category,monthly_cents:amount}); } setEditing(null); } catch(err) { setError((err as Error).message); } finally { setBusy(false); } }}>
  {editing === 'new' && <><Field label="Name"><input name="name" required maxLength={100}/></Field><Field label="Group"><select name="group"><option value="flexible">Everyday spending</option><option value="fixed">Fixed & recurring</option><option value="business">Business</option></select></Field><label className="check"><input type="checkbox" name="rollover"/>Roll unused money into next month</label></>}
  <Field label="Monthly amount ($)"><input name="amount" type="number" step="0.01" min="0" max="100000000" required defaultValue={editing === 'new' ? '' : editing.budget/100}/></Field>{editing !== 'new' && <Field label="Apply to"><select name="scope"><option value="month">This month only</option><option value="default">Default monthly amount</option></select></Field>}<FormError error={error}/><Submit busy={busy}/></form></Modal>}</>;
}
